
# Script to reparametrize Multi-Trait Model (MTM) to Recursive Model (RM)
# Written by Pedro Nuñez
# July 2024


library(coda)

# Read samples file generated by postgibbsf90
data <- read.table("postgibbs_samples", header = F)

#t1 = Microbiome (one ASV at a time)
#t2 = Phenotype (e.g., RFI)

names(data)[1] <- "sample"
names(data)[2] <- "iter"
names(data)[3] <- "effects"

# Here the code could change based on the number of random effects in the model
# Random effect 1 (Pen effect)
names(data)[4] <- "varPen_t1"
names(data)[5] <- "varPen_t2"

# Random effect 2 (Animal effect)
names(data)[6] <- "varA_t1"
names(data)[7] <- "covA"
names(data)[8] <- "varA_t2"

# Residual effects
names(data)[9] <- "varE_t1"
names(data)[10] <- "covE"
names(data)[11] <- "varE_t2"

# Structural effect - Lambda
names(data)[12] <- "lambda"

# Calculate variance components
# Total heritability (h2t)
data$varP <- (data$varA_t2 + data$varE_t2 + data$varPen_t2) #Phenotypic variance trait 2
data$h2t <- (data$varA_t1 / data$varP)

# Microbial heritability (h2m)
data$h2m <- (data$varA_t1 / (data$varA_t1 + data$varE_t1 + data$varPen_t1))

# Direct heritability (h2d)
## We need to get first the indirect effect!!

# Create columns before to start the reparametrization
data$varPen_t1_star <- NA
data$varPen_t2_star <- NA
data$covPen_star <- NA

data$varA_t1_star <- NA
data$varA_t2_star <- NA
data$covA_star <- NA

data$varE_t1_star <- NA
data$varE_t2_star <- NA
data$covE_star <- NA


# Under a Bayesian approach, each iteration is a sample from a posterior marginal distribution
# In a loop we tranform the variance component from MultiTrait Model (MTM) to Recursive Model (RM) following Varona et al. (2024)
# We get the chains of variance components under RM

for (i in 1:nrow(data)){

  ## Step 1: Create matrices (random, residuals and lambda effects)

  #Variance-Covariance matrix for Random effect 1 (Pen effect)
  Pen_MTM <- matrix(c(data$varPen_t1[i], 0,
                      0, data$varPen_t2[i]), nrow = 2, ncol = 2)

  #Variance-Covariance matrix for Random effect 2 (Animal effect)
  G_MTM <- matrix(c(data$varA_t1[i], data$covA[i],
                    data$covA[i], data$varA_t2[i]), nrow = 2, ncol = 2)

  #Variance-Covariance matrix for Residual effects
  R_MTM <- matrix(c(data$varE_t1[i], data$covE[i],
                    data$covE[i], data$varE_t2[i]), nrow = 2, ncol = 2)

  # Delta matrix for lambda effects
  Delta <- matrix(c(1, -data$lambda[i],
                    0, 1), nrow = 2, ncol = 2) #Delta contains (-lambda)


  ## Step 2: Transform variance components from MTM to RM

  # Compute star matrices of random effects
  Pen_star <- Delta %*% Pen_MTM %*% t(Delta)
  G_star <- Delta %*% G_MTM %*% t(Delta)
  R_star <- Delta %*% R_MTM %*% t(Delta)

  # Random effect 1
  data$varPen_t1_star[i] <- round(Pen_star [1,1], 3)
  data$covPen_star[i] <- round(Pen_star [1,2], 3)
  data$varPen_t2_star[i] <- round(Pen_star [2,2], 3)

  # Random effect 2
  data$varA_t1_star[i] <- round(G_star [1,1], 3)
  data$covA_star[i]   <- round(G_star [1,2], 3)
  data$varA_t2_star[i] <- round(G_star [2,2], 3)

  # Residual effects
  data$varE_t1_star[i] <- round(R_star [1,1], 3)
  data$covE_star[i]   <- round(R_star [1,2], 3)
  data$varE_t2_star[i] <- round(R_star [2,2], 3)

}

head(data)

# Now yes!, we can calculate the direct heritability (h2d)
data$h2d <- (data$varA_t2_star / data$varP)

# Create a database (stats), to include the statistics of each chain (mode, mean, median and HPD95)
stats <- as.data.frame(data[1,1])
names(stats)[1] <- "iter"

# Create function to get the mode
get_mode <- function(x) {
  # Round values to three decimal places for consistency
  x <- round(x, 3)

  # Remove NA values
  x <- na.omit(x)

  # Create a frequency table of the values
  freq_table <- table(x)

  # Find the mode(s) with the highest frequency
  mode_value <- as.numeric(names(freq_table[freq_table == max(freq_table)]))

  # Return the median of mode(s) in case of ties
  return(median(mode_value))
}


# Calculate the mean, median, mode and HPD95.
# First we have all the variance components under MTM and then, under RM.

# Stats for Random effect 1 (trait 1 and 2)
stats$varPen_t1 <- round(mean(data$varPen_t1), 3)
stats$varPen_t1_median <- round(median(data$varPen_t1), 3)
stats$varPen_t1_mode <- round(get_mode(data$varPen_t1), 3)
stats$varPen_t1_HPD1 <- round(HPDinterval(as.mcmc(data$varPen_t1))[1], 3)
stats$varPen_t1_HPD2 <- round(HPDinterval(as.mcmc(data$varPen_t1))[2], 3)

stats$varPen_t2 <- round(mean(data$varPen_t2), 3)
stats$varPen_t2_median <- round(median(data$varPen_t2), 3)
stats$varPen_t2_mode <- round(get_mode(data$varPen_t2), 3)
stats$varPen_t2_HPD1 <- round(HPDinterval(as.mcmc(data$varPen_t2))[1], 3)
stats$varPen_t2_HPD2 <- round(HPDinterval(as.mcmc(data$varPen_t2))[2], 3)

# Stats for Random effect 2 (trait 1 and 2)
stats$varA_t1 <- round(mean(data$varA_t1), 3)
stats$varA_t1_median <- round(median(data$varA_t1), 3)
stats$varA_t1_mode <- round(get_mode(data$varA_t1), 3)
stats$varA_t1_HPD1 <- round(HPDinterval(as.mcmc(data$varA_t1))[1], 3)
stats$varA_t1_HPD2 <- round(HPDinterval(as.mcmc(data$varA_t1))[2], 3)

stats$covA <- round(mean(data$covA), 3)
stats$covA_median <- round(median(data$covA), 3)
stats$covA_mode <- round(get_mode(data$covA), 3)
stats$covA_HPD1 <- round(HPDinterval(as.mcmc(data$covA))[1], 3)
stats$covA_HPD2 <- round(HPDinterval(as.mcmc(data$covA))[2], 3)

stats$varA_t2 <- round(mean(data$varA_t2), 3)
stats$varA_t2_median <- round(median(data$varA_t2), 3)
stats$varA_t2_mode <- round(get_mode(data$varA_t2), 3)
stats$varA_t2_HPD1 <- round(HPDinterval(as.mcmc(data$varA_t2))[1], 3)
stats$varA_t2_HPD2 <- round(HPDinterval(as.mcmc(data$varA_t2))[2], 3)

# Stats for Residual effects (trait 1 and 2)
stats$varE_t1<-round(mean(data$varE_t1),3)
stats$varE_t1_median<-round(median(data$varE_t1),3)
stats$varE_t1_mode<-round(get_mode(data$varE_t1),3)
stats$varE_t1_HPD1 <- round(HPDinterval(as.mcmc(data$varE_t1))[1] ,3)
stats$varE_t1_HPD2 <- round(HPDinterval(as.mcmc(data$varE_t1))[2] ,3)

stats$covE <- round(mean(data$covE), 3)
stats$covE_median <- round(median(data$covE), 3)
stats$covE_mode <- round(get_mode(data$covE), 3)
stats$covE_HPD1 <- round(HPDinterval(as.mcmc(data$covE))[1], 3)
stats$covE_HPD2 <- round(HPDinterval(as.mcmc(data$covE))[2], 3)

stats$varE_t2 <- round(mean(data$varE_t2), 3)
stats$varE_t2_median <- round(median(data$varE_t2), 3)
stats$varE_t2_mode <- round(get_mode(data$varE_t2), 3)
stats$varE_t2_HPD1 <- round(HPDinterval(as.mcmc(data$varE_t2))[1], 3)
stats$varE_t2_HPD2 <- round(HPDinterval(as.mcmc(data$varE_t2))[2], 3)

# Stats for Lambda effect (structural coefficients)
stats$lambda <- round(mean(data$lambda),3)
stats$lambda_median <- round(median(data$lambda),3)
stats$lambda_mode <- round(get_mode(data$lambda),3)
stats$lambdaHPD1 <- round(HPDinterval(as.mcmc(data$lambda))[1],3)
stats$lambdaHPD2 <- round(HPDinterval(as.mcmc(data$lambda))[2] ,3)


# Stats reparametrized Random effect 1 (trait 1 and 2)
stats$varPen_t1_star <- round(mean(data$varPen_t1_star), 3)
stats$varPen_t1_star_median <- round(median(data$varPen_t1_star), 3)
stats$varPen_t1_star_mode <- round(get_mode(data$varPen_t1_star), 3)
stats$varPen_t1_star_HPD1 <- round(HPDinterval(as.mcmc(data$varPen_t1_star))[1], 3)
stats$varPen_t1_star_HPD2 <- round(HPDinterval(as.mcmc(data$varPen_t1_star))[2], 3)

stats$varPen_t2_star <- round(mean(data$varPen_t2_star), 3)
stats$varPen_t2_star_median <- round(median(data$varPen_t2_star), 3)
stats$varPen_t2_star_mode <- round(get_mode(data$varPen_t2_star), 3)
stats$varPen_t2_star_HPD1 <-round(HPDinterval(as.mcmc(data$varPen_t2_star))[1], 3)
stats$varPen_t2_star_HPD2 <-round(HPDinterval(as.mcmc(data$varPen_t2_star))[2], 3)

stats$covPen_star <- round(mean(data$covPen_star), 3)
stats$covPen_star_median <- round(median(data$covPen_star), 3)
stats$covPen_star_mode <- round(get_mode(data$covPen_star), 3)
stats$covPen_star_HPD1 <- round(HPDinterval(as.mcmc(data$covPen_star))[1], 3)
stats$covPen_star_HPD2 <- round(HPDinterval(as.mcmc(data$covPen_star))[2], 3)


# Stats reparametrized Random effect 2 (trait 1 and 2)
stats$varA_t1_star <- round(mean(data$varA_t1_star), 3)
stats$varA_t1_star_median <- round(median(data$varA_t1_star), 3)
stats$varA_t1_star_mode <- round(get_mode(data$varA_t1_star), 3)
stats$varA_t1_star_HPD1 <- round(HPDinterval(as.mcmc(data$varA_t1_star))[1], 3)
stats$varA_t1_star_HPD2 <- round(HPDinterval(as.mcmc(data$varA_t1_star))[2], 3)

stats$varA_t2_star <- round(mean(data$varA_t2_star), 3)
stats$varA_t2_star_median <- round(median(data$varA_t2_star), 3)
stats$varA_t2_star_mode <- round(get_mode(data$varA_t2_star), 3)
stats$varA_t2_star_HPD1 <- round(HPDinterval(as.mcmc(data$varA_t2_star))[1], 3)
stats$varA_t2_star_HPD2 <- round(HPDinterval(as.mcmc(data$varA_t2_star))[2],3)

stats$covA_star <- round(mean(data$covA_star), 3)
stats$covA_star_median <- round(median(data$covA_star), 3)
stats$covA_star_mode <- round(get_mode(data$covA_star), 3)
stats$covA_star_HPD1 <- round(HPDinterval(as.mcmc(data$covA_star))[1], 3)
stats$covA_star_HPD2 <- round(HPDinterval(as.mcmc(data$covA_star))[2], 3)


# Stats reparametrized Residual effects (trait 1 and 2)
stats$varE_t1_star <- round(mean(data$varE_t1_star), 3)
stats$varE_t1_star_median <- round(median(data$varE_t1_star), 3)
stats$varE_t1_star_mode <- round(get_mode(data$varE_t1_star), 3)
stats$varE_t1_star_HPD1 <- round(HPDinterval(as.mcmc(data$varE_t1_star))[1], 3)
stats$varE_t1_star_HPD2 <- round(HPDinterval(as.mcmc(data$varE_t1_star))[2], 3)

stats$varE_t2_star <- round(mean(data$varE_t2_star), 3)
stats$varE_t2_star_median <- round(median(data$varE_t2_star), 3)
stats$varE_t2_star_mode <- round(get_mode(data$varE_t2_star), 3)
stats$varE_t2_star_HPD1 <- round(HPDinterval(as.mcmc(data$varE_t2_star))[1], 3)
stats$varE_t2_star_HPD2 <- round(HPDinterval(as.mcmc(data$varE_t2_star))[2], 3)

stats$covE_star <- round(mean(data$covE_star), 3)
stats$covE_star_median <- round(median(data$covE_star), 3)
stats$covE_star_mode <- round(get_mode(data$covE_star), 3)
stats$covE_star_HPD1 <- round(HPDinterval(as.mcmc(data$covE_star))[1], 3)
stats$covE_star_HPD2 <- round(HPDinterval(as.mcmc(data$covE_star))[2], 3)


# Stats for parameter estimations (h2m, h2d, and h2t)
stats$h2m <- round(mean(data$h2m), 3)
stats$h2m_median <- round(median(data$h2m), 3)
stats$h2m_mode <- round(get_mode(data$h2m), 3)
stats$h2m_HPD1 <- round(HPDinterval(as.mcmc(data$h2m))[1], 3)
stats$h2m_HPD2 <- round(HPDinterval(as.mcmc(data$h2m))[2], 3)

stats$h2d <- round(mean( data$h2d), 3)
stats$h2d_median <- round( median(data$h2d), 3)
stats$h2d_mode <- round( get_mode(data$h2d), 3)
stats$h2d_HPD1 <- round(HPDinterval(as.mcmc(data$h2d))[1], 3)
stats$h2d_HPD2 <- round(HPDinterval(as.mcmc(data$h2d))[2], 3)

stats$h2t <- round(mean(data$h2t), 3)
stats$h2t_median <- round (median(data$h2t), 3)
stats$h2t_mode <- round(get_mode(data$h2t), 3)
stats$h2t_HPD1 <- round(HPDinterval(as.mcmc(data$h2t))[1], 3)
stats$h2t_HPD2 <- round(HPDinterval(as.mcmc(data$h2t))[2], 3)


# Save results
write.table(b, file = "chains.txt", col.names = T, row.names = F)
write.table(stats, file = "results_gibbs.txt", col.names = F, row.names = F) #File with statistics (only one value per component)
write.table(names(stats), "ref_names.txt")

